# Generated by Django 5.0.4 on 2024-04-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('script', models.TextField(help_text='Python code to define the process behavior')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='simulations.process')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('time', 'Time'), ('capital', 'Capital')], default='time', max_length=50)),
                ('capacity', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='simulations.simulation')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='simulations.simulation'),
        ),
        migrations.CreateModel(
            name='EnvironmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(default=0, help_text='Simulation start time')),
                ('end_time', models.FloatField(help_text='Simulation end time')),
                ('time_step', models.FloatField(default=1, help_text='Time step used for incremental simulation updates')),
                ('simulation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='environment_settings', to='simulations.simulation')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='simulations.simulation')),
            ],
        ),
        migrations.AddField(
            model_name='simulation',
            name='simulation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='simulations.simulationtype'),
        ),
    ]
